spring.datasource.url=jdbc:postgresql://${DB_HOST_POSTGRES}/${DB_NAME_POSTGRES}
spring.datasource.username=${DB_USER_POSTGRES}
spring.datasource.password=${DB_PASSWORD_POSTGRES}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update